### PR TITLE
Fix pulseshitter streaming the microphone when locale is not English

### PR DESCRIPTION
**Pull request by LyesSaadi**
Previously, pulshitter failed to detect when a process closed its sink when parec's output was translated to another language. This forces parec's output to be in English, solving the issue.

### CODE REVIEW

**Comment by LyesSaadi** [comment]
Confirmed this fixes the issue on my side from my quick testing.

**Comment by Enitoni** [comment]
Before I merge this, could you make sure you've added the `LANG=C` env variable to all the pactl spawning instances containing `LC_NUMERIC` in `/audio/pulse.rs` ?

These commands are also sensitive to localization, so just to be on the safe side they should also be normalized to english.

**Comment by LyesSaadi** [comment]
Good idea ! Will do this !

**Comment by LyesSaadi** [comment]
Oh this panics:
```
thread 'main' panicked at 'spawns pactl: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/audio/pulse.rs:616:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LyesSaadi** [comment]
Oh, no, my bad, this is an error on my side.

**Comment by LyesSaadi** [comment]
Yeah, I can confirm it works fine on my side !

**Comment by Enitoni** [comment]
Appreciated! Thanks.

**Pull request merged**
